//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SMEyeApp.rc
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SMEYEAPP_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_PATIENT_INFO         130
#define IDD_DIALOG_SUBJECT_INFO         131
#define IDD_DIALOG_RESULT_LIST          132
#define IDD_DIALOG_ANALYZE              133
#define IDD_DIALOG_ANAL_NYSTAG          135
#define IDD_DIALOG1                     137
#define IDD_DIALOG_TEST_OPTION          137
#define IDR_CONTEXT_TEST_LIST_CHILD     138
#define IDR_CONTEXT_TEST_LIST_BLANK     139
#define IDD_DIALOG_ENTER_NEW_NAME       141
#define IDR_CONTEXT_TEST_LIST_GROUP     142
#define IDD_DIALOG2                     143
#define IDD_DIALOG3                     144
#define IDD_DIALOG_ANALYZE_CALIBRATION  144
#define IDD_DIALOG_ANALYZE_SACCADE      146
#define IDD_DIALOG_APP_OPTION           148
#define IDR_CONTEXT_IMAGE               149
#define IDD_DIALOG_ANALYZE_PURSUIT      154
#define IDD_DIALOG_CALORIC              158
#define IDD_DIALOG_ANALYZE_CALORIC      158
#define IDR_CONTEXT_CHART_POS           159
#define IDD_DIALOG_CUSTOM_CALIBRATION_SETTING 160
#define IDD_DIALOG_PRINT_SETUP          161
#define IDD_DIALOG_MAKE_TCHART_IMAGE    162
#define IDR_CONTEXT_CALORIC_FIX         166
#define IDD_DIALOG_SPON_COMPENSATION    167
#define IDD_DIALOG_ANALYZE_HEAD_THRUST  168
#define IDD_DIALOG_HEAD_THRUST_OPTION   170
#define IDC_TCHART_HORIZONTAL           1000
#define IDC_TCHART_VERTICAL             1001
#define IDC_TCHART_TORSIONAL            1002
#define IDC_TCHART_RADIUS               1003
#define IDC_TCHART_ACC                  1004
#define IDC_CHECK_CAM_START             1006
#define IDC_STATIC_TEST_TIME            1007
#define IDC_STATIC_FRAME_INFO           1008
#define IDC_STATIC_THRES_INFO           1009
#define IDC_CHECK_SAVE_IMAGE            1010
#define IDC_BUTTON_RESET_TORSION        1011
#define IDC_STATIC_EYE_IMAGE_DISPLAY    1012
#define IDC_TREE_TEST                   1013
#define IDC_BUTTON_EDIT_SUBJECT_INFO    1014
#define IDC_BUTTON4                     1015
#define IDC_BUTTON_EDIT_TEST_INFO       1015
#define IDC_STATIC_GROUP_SI             1016
#define IDC_STATIC_SUBJECT_INFO         1017
#define IDC_STATIC_GROUP_TI             1018
#define IDC_STATIC_TEST_INFO            1019
#define IDC_BUTTON1                     1020
#define IDC_BUTTON2                     1021
#define IDC_RADIO_FEMAIL                1021
#define IDC_RADIO_FEMALE                1021
#define IDC_RADIO_MALE                  1022
#define IDC_STATIC_GROUP_EYE_INFO       1022
#define IDC_BUTTON5                     1022
#define IDC_BUTTON_SELECT_NONE          1022
#define IDC_EDIT_PATIENT_NAME           1023
#define IDC_STATIC_GROUP_CAM_INFO       1023
#define IDC_EDIT_PATIENT_ID             1024
#define IDC_BUTTON_NEW_SUBJECT_INFO     1024
#define IDC_EDIT_PATIENT_AGE            1025
#define IDC_STATIC_PATIENT_DATE         1026
#define IDC_EDIT_PATIENT_MEMO           1027
#define IDC_EDIT_DOCTOR_NAME            1028
#define IDC_RADIO2IDC_RADIO_MALE        1029
#define IDC_EDIT_TESTER_NAME            1029
#define IDC_LIST_TEST_LIST              1031
#define IDC_STATIC_LIST_MEMO            1032
#define IDC_EDIT4                       1033
#define IDC_BUTTON3                     1033
#define IDC_BUTTON_OPEN                 1033
#define IDC_STATIC_CAM_INFO             1034
#define IDC_STATIC_CAM_INFO2            1035
#define IDC_STATIC_EYE_INFO             1035
#define IDC_TCHART1                     1035
#define IDC_TCHART_ANAL                 1035
#define IDC_TCHART_ANAL0                1035
#define IDC_TCHART_AN_0                 1035
#define IDC_TCHART_AC_LEFT_RAW          1035
#define IDC_TCHART_AS_ZOOM_LEFT         1035
#define IDC_TCHART_AS_ZOOM              1035
#define IDC_TCHART_AP_POSITION          1035
#define IDC_TCHART_ACE_POSITION         1035
#define IDC_TCHART_IMAGE                1035
#define IDC_TCHART_AC_LEFT_RAW2         1035
#define IDC_TCHART_CALORIC_BUTTERFLY    1035
#define IDC_TCHART_HT_LEFT_UP           1035
#define IDC_TCHART2                     1036
#define IDC_BUTTON_ANALYZE              1036
#define IDC_TCHART_ANAL1                1036
#define IDC_TCHART_AN_1                 1036
#define IDC_TCHART_AC_LEFT_CALIB        1036
#define IDC_TCHART_AS_PEAK_VEL_LEFT     1036
#define IDC_TCHART_AS_PEAK_VEL          1036
#define IDC_TCHART_AP_VELOCITY          1036
#define IDC_TCHART_ACE_POSITION2        1036
#define IDC_TCHART_ACE_NYS_SLOW_VEL     1036
#define IDC_TCHART_CALORIC_LEFT_WARM    1036
#define IDC_TCHART_CALORIC_SLOW_MOVE    1036
#define IDC_TCHART_HT_RIGHT_UP          1036
#define IDC_TCHART3                     1037
#define IDC_TCHART_ANAL2                1037
#define IDC_TCHART_ANALYZE_0            1037
#define IDC_TCHART_ANAL_NYSTAG_2        1037
#define IDC_TCHART_AN_2                 1037
#define IDC_TCHART_AC_RIGHT_RAW         1037
#define IDC_TCHART_AS_ACCURACY_LEFT     1037
#define IDC_TCHART_AS_ACCURACY          1037
#define IDC_TCHART_AP_VELOCITY2         1037
#define IDC_TCHART_AP_GAIN              1037
#define IDC_TCHART_CALORIC_RIGHT_COOL   1037
#define IDC_TCHART_HT_LEFT_DOWN         1037
#define IDC_STATIC_RESULT               1038
#define IDC_BUTTON_OPTION               1038
#define IDC_TCHART_AC_RIGHT_CALIB       1038
#define IDC_TCHART_AS_LATENCY_LEFT      1038
#define IDC_TCHART_AS_LATENCY           1038
#define IDC_TCHART_CALORIC_LEFT_COOL    1038
#define IDC_TCHART_HT_RIGHT_DOWN        1038
#define IDC_TCHART_ANAL3                1039
#define IDC_TCHART_AC_H                 1039
#define IDC_BUTTON_OPEN2                1039
#define IDC_BUTTON_PRINT                1039
#define IDC_TCHART_CALORIC_LEFT_WARM4   1039
#define IDC_TCHART_CALORIC_RIGHT_WARM   1039
#define IDC_TCHART_HT_LEFT_UP_VEL       1039
#define IDC_TCHART_ANAL4                1040
#define IDC_CHECK_EYE_LEFT              1040
#define IDC_TCHART_AC_V                 1040
#define IDC_TCHART_HT_RIGHT_UP_VEL      1040
#define IDC_TCHART_ANAL5                1041
#define IDC_CHECK_EYE_RIGHT             1041
#define IDC_TCHART_HT_LEFT_DOWN_VEL     1041
#define IDC_TCHART_ANAL6                1042
#define IDC_CHECK_ACC_X                 1042
#define IDC_TCHART_HT_RIGHT_DOWN_VEL    1042
#define IDC_TCHART_ANAL7                1043
#define IDC_CHECK_ACC_Y                 1043
#define IDC_TCHART_AS_ZOOM_RIGHT        1043
#define IDC_CHECK_ACC_Z                 1044
#define IDC_TCHART_AS_PEAK_VEL_RIGHT    1044
#define IDC_CHECK_GYRO_X                1045
#define IDC_TCHART_AS_ACCURACY_RIGHT    1045
#define IDC_CHECK_GYRO_Y                1046
#define IDC_TCHART_AS_LATENCY_RIGHT     1046
#define IDC_CHECK_CHART_H               1047
#define IDC_CHECK_CHART_V               1048
#define IDC_CHECK_CHART_T               1049
#define IDC_CHECK_CHART_R               1050
#define IDC_CHECK_CHART_ACC             1051
#define IDC_CHECK_CHART_H6              1052
#define IDC_CHECK_CHART_H7              1053
#define IDC_CHECK_CHART_H8              1054
#define IDC_STATIC_EYE_LEFT_COLOR       1055
#define IDC_STATIC_SERIES_EYE_LEFT_COLOR 1056
#define IDC_STATIC_SERIES_EYE_RIGHT_COLOR 1057
#define IDC_LIST_RESULT                 1057
#define IDC_LIST_RESULT_SUMMARY         1057
#define IDC_STATIC_SERIES_ACC_X_COLOR3  1058
#define IDC_RADIO_AN_LEFT               1058
#define IDC_STATIC_SERIES_ACC_Y_COLOR   1059
#define IDC_RADIO_AN_RIGHT              1059
#define IDC_STATIC_SERIES_ACC_Z_COLOR   1060
#define IDC_RADIO_AN_RIGHT2             1060
#define IDC_RADIO_AN_ALL                1060
#define IDC_STATIC_SERIES_GYRO_X_COLOR6 1061
#define IDC_LIST_AN_RESULT_SUMMARY      1061
#define IDC_STATIC_SERIES_ACC_X_COLOR7  1062
#define IDC_STATIC_SERIES_GYRO_Y_COLOR7 1062
#define IDC_LIST_AN_RESULT_SUMMARY2     1062
#define IDC_LIST_AN_RESULT_DETAIL       1062
#define IDC_EDIT_TEST_NAME              1063
#define IDC_COMBO_ANAL_METHOD           1064
#define IDC_COMBO_ANAL_COMPONENT        1065
#define IDC_COMBO_STIMULATION_LIST      1066
#define IDC_RADIO_STI_CALIBRATION       1068
#define IDC_RADIO_STI_GAZE_A            1069
#define IDC_RADIO_STI_GAZE_B            1070
#define IDC_RADIO_STI_PURSUIT           1071
#define IDC_RADIO_STI_SACCADE_A         1072
#define IDC_RADIO_STI_SACCADE_B         1073
#define IDC_RADIO_STI_SACCADE_RANDOM    1074
#define IDC_RADIO_STI_OKN               1075
#define IDC_RADIO_STI_LED               1076
#define IDC_RADIO_STI_NO                1077
#define IDC_STATIC_STIMULATION_PROTOCOLE 1080
#define IDC_STATIC_STI_DESCRIPTION      1081
#define IDC_CHECK_REAL_TIME_ANAL        1082
#define IDC_EDIT_NEW_NAME               1083
#define IDC_COMBO_COM_SELECT_ACC        1084
#define IDC_COMBO_COM_SELECT_ACC2       1085
#define IDC_COMBO_COM_SELECT_STI        1085
#define IDC_STATIC_AC_MODEL_COEFF_H     1086
#define IDC_STATIC_AC_MODEL_COEFF_V     1087
#define IDC_STATIC_AS_RESULT_LEFT       1087
#define IDC_LIST_AS_RESULT_LEFT         1088
#define IDC_LIST_AS_RESULT_SUMMARY      1088
#define IDC_STATIC_AS_RESULT_RIGHT      1089
#define IDC_LIST_AS_RESULT_RIGHT        1090
#define IDC_LIST_AS_RESULT_DETAIL       1090
#define IDC_TCHART4                     1091
#define IDC_TCHART_AS_DATA              1091
#define IDC_TCHART_HEAD_THRUST_MAIN     1091
#define IDC_RADIO_AS_ALL                1092
#define IDC_RADIO_AS_LEFT               1093
#define IDC_COMBO_COMPORT_TARGET        1093
#define IDC_RADIO_AS_RIGHT              1094
#define IDC_COMBO_COMPORT_ACCELERATION  1094
#define IDC_STATIC_DATA_FOLDER          1095
#define IDC_CHECK1                      1096
#define IDC_CHECK_SAVE_VIDEO            1096
#define IDC_CHECK_CUSTOM_CALIBRATION    1096
#define IDC_CHECK_USE_FIX_BLOCK         1096
#define IDC_CHECK_REMOVE_OFFSET         1096
#define IDC_CHECK_LIMIT_MAX_HEAD_SPEED  1096
#define IDC_BUTTON_CHANGE_DATA_FOLDER   1097
#define IDC_CHECK_USE_FIX_BLOCK_LW      1097
#define IDC_RADIO_IMAGE_LEFT_RIGHT      1098
#define IDC_CHECK_USE_FIX_BLOCK_RC      1098
#define IDC_RADIO_IMAGE_RIGHT_LEFT      1099
#define IDC_RADIO_AP_ALL                1099
#define IDC_CHECK_USE_FIX_BLOCK_LC      1099
#define IDC_RADIO_AP_LEFT               1100
#define IDC_CHECK_USE_FIX_BLOCK_RW      1100
#define IDC_RADIO3                      1101
#define IDC_RADIO_AP_RIGHT              1101
#define IDC_LIST_AP_RESULT_SUMMARY      1103
#define IDC_LIST_AP_RESULT_DETAIL       1104
#define IDC_RADIO_STI_CALORIC           1104
#define IDC_RADIO_ACE_ALL               1105
#define IDC_RADIO_ACE_LEFT              1106
#define IDC_RADIO_ACE_RIGHT             1107
#define IDC_LIST_ACE_RESULT_SUMMARY     1108
#define IDC_LIST_ACE_RESULT_DETAIL      1109
#define IDC_EDIT_SPON_MANUAL_LEFT_VALUE 1109
#define IDC_BUTTON_AC_SAVE              1110
#define IDC_EDIT_SPON_MANUAL_RIGHT_VALUE 1110
#define IDC_BUTTON_OPTION_CALIBRATION_LOAD 1111
#define IDC_STATIC_OPTION_CALIB_COEFF   1112
#define IDC_CHECK_SELECT_CODEC_BY_USER  1113
#define IDC_BUTTON_AS_REFRESH           1114
#define IDC_BUTTON_AP_REFRESH           1115
#define IDC_BUTTON_AN_REFRESH           1116
#define IDC_CHECK                       1117
#define IDC_CHECK_SWITCH_CAMERAS        1117
#define IDC_BUTTON_NYSTAG_PRINT         1117
#define IDC_STATIC_LR_DEGREE            1118
#define IDC_STATIC_TB_DEGREE            1119
#define IDC_EDIT_CUSTOM_LR              1120
#define IDC_EDIT_CUSTOM_TB              1121
#define IDC_BUTTON_CUSTOM_ANALYZE       1122
#define IDC_BUTTON_CUSTOM_CALIBRATION_SETTING 1123
#define IDC_BUTTON_CUSTOM_CALIBRATION_ANALYZE 1124
#define IDC_CHECK2                      1124
#define IDC_CHECK_USE_EOG               1124
#define IDC_CHECK_SPONTANEOUS_NYSTAG    1124
#define IDC_COMBO_COMPORT_EOG           1125
#define IDC_TREE1                       1127
#define IDC_TREE_PRINT                  1127
#define IDC_TREE_SELECT_COMPENSATION    1127
#define IDC_BUTTON_SELECT_ALL           1128
#define IDC_STATIC_SPONTANEOUS_NYSTAG_VALUE 1130
#define IDC_RADIO_CALORIC_LEFT_EYE      1131
#define IDC_RADIO_CALORIC_RIGHT_EYE     1132
#define IDC_BUTTON_SELECT_SPONTANEOUS_TEST 1133
#define IDC_LIST_TESTS_RESULT           1135
#define IDC_LIST_TESTS_SUMMARY          1136
#define IDC_RADIO_SPON_MANUAL_SELECT    1136
#define IDC_RADIO_SPON_TEST_SELECT      1137
#define IDC_EDIT_SPON_VALUE             1138
#define IDC_STATIC_SIGN                 1139
#define IDC_EDIT_SPON_TEST_LEFT_VALUE   1140
#define IDC_EDIT_SPON_TEST_RIGHT_VALUE  1141
#define IDC_BUTTON_RESET_PEAK           1141
#define IDC_RADIO_MANUAL_PEAK_NONE      1142
#define IDC_RADIO_MANUAL_PEAK_X         1143
#define IDC_RADIO4                      1144
#define IDC_RADIO_MANUAL_PEAK_XY        1144
#define IDC_LIST_HT_UP                  1145
#define IDC_BUTTON_HT_REANALYZE         1146
#define IDC_BUTTON_CALORIC_REANALYZE    1147
#define IDC_BUTTON_CALORIC_REANALYZE2   1148
#define IDC_BUTTON_CALORIC_PRINT        1148
#define IDC_EDIT_LIMIT_MAX_HEAD_SPEED   1148
#define IDC_BUTTON_HEAD_THRUST_OPTION   1149
#define IDC_EDIT_LIMIT_MIN_HEAD_SPEED   1149
#define IDC_LIST_HT_RIGHT_DOWN          1150
#define IDC_LIST_HT_DOWN                1150
#define IDC_STATIC_MAX_HEAD_SPEAD       1150
#define IDC_LIST_HT_SUMMARY             1151
#define IDC_STATIC_MIN_HEAD_SPEAD       1151
#define IDC_BUTTON_SACCADE_PRINT        1151
#define IDC_BUTTON_PURSUIT_PRINT        1152
#define IDC_BUTTON_HT_PRINT             1153
#define IDC_BUTTON_EVENT1               1154
#define IDC_BUTTON_EVENT2               1155
#define IDC_BUTTON_EVENT3               1156
#define IDC_BUTTON_EVENT4               1157
#define IDC_BUTTON_EVENT5               1158
#define IDC_BUTTON_EVENT6               1159
#define IDC_BUTTON_EVENT7               1160
#define IDC_BUTTON_EVENT8               1161
#define IDC_BUTTON_EVENT9               1162
#define IDC_LIST_EVENT                  1164
#define IDC_BUTTON_EVENT_LOAD           1166
#define IDC_BUTTON_EVENT_IMPORT         1166
#define IDC_BUTTON_EVENT_EXPORT         1167
#define IDC_BUTTON_DELETE_POSITIVE      1168
#define IDC_BUTTON_DELETE_NEGATIE       1169
#define IDC_BUTTON_DELETE_NEGATIVE      1169
#define ID_EDIT_TEST_INFO               32772
#define ID_SETASDEFAULT_TEST_INFO       32774
#define ID_BLANK_ADDNEWGROUP            32775
#define ID_BLANK_DELETE                 32776
#define ID_EDITTEST_DELETE              32777
#define ID_CONTEXT_GROUP_RENAME         32780
#define ID_CONTEXT_GROUP_DELETE         32781
#define ID_CONTEXT_BLANK_CLEAR          32783
#define ID_CONTEXT_BLANK_LOAD           32786
#define ID_CONTEXT_BLANK_SAVE           32787
#define ID_CONTEXT_GROUP_ADD_TEST       32789
#define ID_CHILD_CLEARDATA              32790
#define ID_CONTEXT_IMAGE_RESET_TORSION  32793
#define ID_CONTEXT_IMAGE_FLIP_LR_EYE    32794
#define ID_CHARTPOS_REMOVEOFFSET        32795
#define ID_CHARTPOS_SHOWOFFSET          32796
#define ID_CONTEXT_CALORIC_SET_FIX_BLOCK 32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1169
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
